make auth layout
forma-web/cyrille-frontend pull request #41
Opened 2023-10-15 18:49 UTC by DaVas255

2023-10-18 12:12 UTC, robonen requested changes
Написал где нужно поправить

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +        <span class="italic">the future reading</span> realm.
В html есть тег `i` для курсива

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +@import url('https://fonts.cdnfonts.com/css/sf-pro-display');
Шрифт уже подключен глобально, тут это не нужно делать

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +.block__auth {
Мы используем scss, принято вкладывать классы в родительский
```scss
.block {
  &__auth {}
}
```

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +  width: 50%;
`width: 50%`, лучше заменить на логическое значение `flex: 1`

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +  width: 50%;
Аналогично `flex: 1`

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +  background-image: url(../public/backgrounds/auth.png);
Для файлов в папке public путь начинается с `/`, в данном случае `/backgrounds/auth.png`

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +
`background-position: center`

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +  font-family: 'SF Pro Display', sans-serif;
Опять же, шрифт уже указан глобально

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +  background: linear-gradient(
Судя по макету, градиент там не только под текстом, а на все изображение. Поэтому его нужно перенести в стили изображения

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +.italic {
Стили такого шрифта нужно вынести глобально, он много где используется. `font-style` не нужен

2023-10-18 12:12 UTC, robonen commented on src/layouts/auth.vue
> +  font-family: Georgia;
Для `font-family` всегда нужно указывать резервный шрифт, хотя бы `Georgia, serif`

2023-10-19 08:43 UTC, RomaFedoro commented on src/layouts/auth.vue
> +        <span class="italic">the future reading</span> realm.
А потом Апа придумает, что шрифт должен быть жирный с курсивом и мы это ещё в `b` обернем

2023-10-19 08:50 UTC, RomaFedoro commented on src/layouts/auth.vue
> +.italic {
Тут скорее нужно название для класса поменять, оно ничего бизнесового не говорит

2023-10-26 11:05 UTC, robonen requested changes

2023-10-26 11:05 UTC, robonen commented on src/components/AuthHeader.vue
> +    width: 1.5vw;
Размер надо сделать в `rem`

2023-10-26 11:05 UTC, robonen commented on src/components/AuthHeader.vue
> +  padding: 3%;
Тут еще нужно вертикальное выравнивание и `padding` тоже лучше в `rem`

2023-11-10 16:16 UTC, robonen approved these changes

2023-11-10 16:17 UTC, merged